//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AudienceClassification
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AudienceClassification()
        {
            this.Movie = new HashSet<Movie>();
        }
    
        public int AudienceClassificationId { get; set; }
        
        [Display(Name = "Nombre de audiencia")]
        public string Name { get; set; }
        
        [Display(Name = "Acrónimo")]
        public string Acronym { get; set; }
        
        [Display(Name = "Descripción")]
        public string Descripcion { get; set; }
        
        [Display(Name = "Restricción")]
        public int Restriction { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movie> Movie { get; set; }
    }
}
