//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class CinemaSchedule
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CinemaSchedule()
        {
            this.CinemaScheduleHistory = new HashSet<CinemaScheduleHistory>();
        }
    
        public int CinemaScheduleId { get; set; }
        public int CinemaId { get; set; }
        public int MovieFormatId { get; set; }
        public int MovieId { get; set; }

        [Display(Name = "Fecha de inicio")]
        public System.DateTime BeginDatetime { get; set; }

        [Display(Name = "Fecha final")]
        public System.DateTime FinishDatetime { get; set; }
    
        public virtual Cinema Cinema { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinemaScheduleHistory> CinemaScheduleHistory { get; set; }
        public virtual Movie Movie { get; set; }
        public virtual MovieFormat MovieFormat { get; set; }
    }
}
