//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AudienceClassification> AudienceClassification { get; set; }
        public virtual DbSet<Cinema> Cinema { get; set; }
        public virtual DbSet<CinemaSchedule> CinemaSchedule { get; set; }
        public virtual DbSet<CinemaScheduleHistory> CinemaScheduleHistory { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<FoodHistory> FoodHistory { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
        public virtual DbSet<MovieCategory> MovieCategory { get; set; }
        public virtual DbSet<MovieFormat> MovieFormat { get; set; }
        public virtual DbSet<MoviePrice> MoviePrice { get; set; }
        public virtual DbSet<Sale> Sale { get; set; }
        public virtual DbSet<SaleDetails> SaleDetails { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Parameter> Parameter { get; set; }
    
        public virtual ObjectResult<sp_GetFoodInventary_Result> sp_GetFoodInventary()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetFoodInventary_Result>("sp_GetFoodInventary");
        }
    
        public virtual ObjectResult<sp_GetAvailableMovies_Result> sp_GetAvailableMovies()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_GetAvailableMovies_Result>("sp_GetAvailableMovies");
        }
    }
}
