//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cinema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cinema()
        {
            this.CinemaSchedule = new HashSet<CinemaSchedule>();
        }
    
        public int CinemaId { get; set; }
        public int MovieFormatId { get; set; }
        public string Name { get; set; }
        public int Capacity { get; set; }
        public int CinemaDesignId { get; set; }
    
        public virtual MovieFormat MovieFormat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CinemaSchedule> CinemaSchedule { get; set; }
    }
}
