//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CinemaScheduleHistory
    {
        public int CinemaScheduleHistoryId { get; set; }
        public int CinemaScheduleId { get; set; }
        public int TicketId { get; set; }
        public string JsonDetails { get; set; }
        public int CinemaScheduleState { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual CinemaSchedule CinemaSchedule { get; set; }
    }
}
