//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodHistory
    {
        public long FoodHistoryId { get; set; }
        public long FoodId { get; set; }
        public decimal Price { get; set; }
        public int QuantityAvailable { get; set; }
        public int QuantityChanged { get; set; }
        public int Status { get; set; }
        public string UserName { get; set; }
        public string Description { get; set; }
        public System.DateTime ModificationDate { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
