//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieCategory
    {
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public long BitAssigned { get; set; }
        public short Status { get; set; }
    }
}
