//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoviePrice
    {
        public int MovieFormatId { get; set; }
        public decimal Price { get; set; }
        public string Name { get; set; }
    
        public virtual MovieFormat MovieFormat { get; set; }
    }
}
