//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicoCinema.WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public long SaleId { get; set; }
        public long PaymentNumber { get; set; }
        public string UserName { get; set; }
        public System.DateTime RegisterDate { get; set; }
    
        public virtual SaleDetails SaleDetails { get; set; }
    }
}
